modLoader="javafml"
loaderVersion="[39,)"
license="All Rights Reserved"
issueTrackerURL="https://github.com/BigVirusBoi/Bobs-Weed-Mod/issues"

[[mods]]
modId="bobs_weed_mod"
version="${file.jarVersion}"
displayName="Bob's Weed Mod"
#updateJSONURL=""
#displayURL=""
logoFile="logo.png"
credits="BigVirusBoi"
authors="BigVirusBoi"
description='''
This is a weed mod I made for fun!
PLEASE do NOT take this seriously. I DO NOT ENDORSE DRUGS OR SMOKING OR WEED. This is only made FOR FUN!
'''

[[dependencies.bobs_weed_mod]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bobs_weed_mod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1,1.19)"
ordering = "NONE"
side = "BOTH"